---
collections:
  - name: community.general
    version: 12.1.0
  - name: community.sops
    version: 2.2.7
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.6.2
