apiVersion: apps/v1
kind: Deployment
metadata:
  name: dawarich-app
  namespace: dawarich
  labels:
    app: dawarich-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: dawarich-app
  template:
    metadata:
      labels:
        app: dawarich-app
      annotations:
        configmap.reloader.stakater.com/reload: dawarich-app-entrypoint, dawarich-app-config
        secret.reloader.stakater.com/reload: dawarich-secret
    spec:
      containers:
        - name: dawarich-app
          image: freikin/dawarich:0.37.3
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: dawarich-app-config
            - secretRef:
                name: dawarich-secret
          command: ["/usr/bin/entrypoint.sh", "bin/rails", "server", "-p", "3000", "-b", "::"]
          resources:
            requests:
              cpu: "100m"
              memory: "1Gi"
            limits:
              memory: "1Gi"
          volumeMounts:
            - name: dawarich-app-entrypoint
              mountPath: /usr/bin/entrypoint.sh
              subPath: entrypoint.sh
            - name: dawarich-public
              mountPath: /var/app/public
            - name: dawarich-watched
              mountPath: /var/app/tmp/imports/watched
            - name: dawarich-storage
              mountPath: /var/app/storage
            - name: dawarich-db-data
              mountPath: /dawarich_db_data
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 30
      volumes:
        - name: dawarich-app-entrypoint
          configMap:
            name: dawarich-app-entrypoint
            defaultMode: 0755
        - name: dawarich-public
          persistentVolumeClaim:
            claimName: dawarich-public
        - name: dawarich-watched
          persistentVolumeClaim:
            claimName: dawarich-watched
        - name: dawarich-storage
          persistentVolumeClaim:
            claimName: dawarich-storage
        - name: dawarich-db-data
          persistentVolumeClaim:
            claimName: dawarich-db-data
