apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wireguard-web
  namespace: vpn
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "wg.${SECRET_DOMAIN}"
      secretName: wg-tls
  rules:
    - host: "wg.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vpn-ip
                port:
                  number: 51821
