apiVersion: v1
kind: Service
metadata:
  name: vpn-ip
  namespace: vpn
spec:
  ports:
    - name: vpn-ip
      port: 51820
      protocol: UDP
      targetPort: 51820
    - name: vpn-web
      port: 51821
      protocol: TCP
      targetPort: 51821
