---
kubernetes:
  children:
    master:
      hosts:
        NUC7PJYHN:
          ansible_host: 192.168.68.98
    worker:
      hosts:
        NUC7PJYHN-rookie:
          ansible_host: 192.168.68.96
        NUC7PJYHN-cripple:
          ansible_host: 192.168.68.97
