---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wg-easy-ui
  namespace: vpn
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "vpn-ui.${SECRET_DOMAIN}"
      secretName: vpn-tls
  rules:
    - host: "vpn-ui.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wg-easy
                port:
                  number: 51821
