#! Service definition for wg-easy, exposes its UDP port as a NodePort service externally on <NodeIP:31820>
apiVersion: v1
kind: Service
metadata:
  name: wg-easy
  namespace: vpn
  labels:
    service: wg-easy
spec:
  type: LoadBalancer
  selector:
    service: wg-easy
  ports:
    - name: wireguard
      port: 51820
      protocol: UDP
    - name: web
      port: 51821
      protocol: TCP
